### ISSUE TITLE
Classification accuracy evaluation

### ISSUE THREAD

**Issue by yanghr** [mfederici/Multi-View-Information-Bottleneck#2]
Great work! Just a small question. I noticed that when evaluating the classification accuracy of the learned feature, you are only using the "mean" of the encoder output to construct the dataset, rather than resampling the feature from the encoder distribution. Is this a common practice for information bottelneck encoder? Or do you have some specific reason for doing this? Thanks!

**Comment by mfederici** [comment]
Thank you for expressing interest in our work and for the relevant question. 
Since the evaluation reported in this work considers the accuracy of a linear classifier, we can use the expectation of the posterior instead of considering a finite number of samples because of the linearity of the expectation: E[Wz]=W E[z]. Using a sampled version could be beneficial when the classifier z->y is not linear, especially if the posterior p(z_1|v_1) is a multimodal distribution.

**Comment by yanghr** [comment]
Hi Marco,

Thanks a lot for your explanation! It answered my question perfectly. Looking forward to meeting you guys at ICLR!

Best,
Huanrui


Sent from my iPhone

On Mar 2, 2020, at 04:42, Marco.Federici <notifications@github.com> wrote:

﻿

Thank you for expressing interest in our work and for the relevant question.
Since the evaluation reported in this work considers the accuracy of a linear classifier, we can use the expectation of the posterior instead of considering a finite number of samples because of the linearity of the expectation: E[Wz]=W E[z]. Using a sampled version could be beneficial when the classifier z->y is not linear, especially if the posterior p(z_1|v_1) is a multimodal distribution.
