### ISSUE TITLE
About other codes of the full experiments

### ISSUE THREAD

**Issue by WayneTomas** [mfederici/Multi-View-Information-Bottleneck#4]
Hello, I am working on the multi-view information bottleneck and attracted by your paper. Could you please make all your codes open source, e.g. SKETCH-BASED IMAGE RETRIEVAL and MIR-FLICKR? Thank you.

**Comment by mfederici** [comment]
Hi, our MIR-FLICKR experiments follow the procedure reported in https://arxiv.org/pdf/1610.03454.pdf, while the experiments for the Sketch-Based Image Retrieval task are based on https://arxiv.org/abs/1903.03372 (images and sketches of the same class are paired randomly at runtime). The architectures are described in detail in Appendix G.2 and G.3, while the training procedure is analogous to the one reported in this repository. 

Since the code and data-loading procedure does not differ fundamentally from previous work we decided not to include them in this repository and focus on the explanation of our procedure on a simple task.

**Comment by WayneTomas** [comment]
Thank you very much for the reply. These details are very helpful to me and other researchers.
